name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run:  echo “Hello readers”

      - name: Run sample script
        uses: echo Hello, world
